### ISSUE TITLE
Union Find Disjoint Sets Implementation In C++

### ISSUE THREAD

**Issue by AbdeltwabMF** [sobhanbera/algorithms#148]
#### This issue is about [Union Find Disjoint Sets](https://github.com/sobhanbera/algorithms/tree/main/data%20structures/cpp/union_find_disjoint_sets.cpp)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues

**Comment by AbdeltwabMF** [comment]
Kindly assign this to me.

**Comment by sobhanbera** [comment]
You have been assigned for this issue. Get Started!
