### ISSUE TITLE
Implement Linear Search in Python

### ISSUE THREAD

**Issue by sobhanbera** [sobhanbera/algorithms#201]
**Algorithm/Data Structure**: Linear Search
**Programming Language**: Python
**Difficulty**: ⭐️⭐️

## Issue Details

**Description**: 
Implement the Linear Search algorithm in Python. Linear Search is a simple searching algorithm that sequentially checks each element of a list until a match is found or the whole list has been searched. Your implementation should correctly search for a specified target element in a list and return its index if found or -1 if not found.

**Additional Information**: 
If you are new to Linear Search or need guidance on implementing it in Python, feel free to ask questions or seek help in the comments. This is a great opportunity for contributors to gain experience in searching algorithms in Python.

**Note**: 
Before starting to work on this issue, please comment below to express your interest and let us know if you have any questions or need clarification on the task.

**Comment by Rohit-sharma04** [comment]
hey , i want to contribute in it could please assign it to me

**Comment by sobhanbera** [comment]
@Rohit-sharma04 assigned. Do let me know if you need any help!

**Comment by Rohit-sharma04** [comment]
linear search in python is already implemented  in the python folder , can i work on selection sort in javascript

**Comment by sobhanbera** [comment]
My bad! Ok, no problem. #205 is assigned to you.
