### ISSUE TITLE
Breadth First Search in C++

### ISSUE THREAD

**Issue by SobhanBera** [SobhanBera/algorithms#32]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by ng29** [comment]
Hey,

Can i take this algo ?

**Comment by iamkumar-gaurav** [comment]
May i have your Permission ??

**Comment by iamkumar-gaurav** [comment]
I will do it after 10min



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by SubhamChoudhury** [comment]
Can I please contribute to this issue?
