### ISSUE TITLE
Depth First Traversal in C++

### ISSUE THREAD

**Issue by SobhanBera** [SobhanBera/algorithms#34]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by shivam2001pandey** [comment]
Assign this issue to me (I want to work on this)

**Comment by shivam2001pandey** [comment]
i am well confident in this algo so please assign this to me

**Comment by shivam2001pandey** [comment]
Thank you for this opportunity.
I have Added Depth First Traversal in C++ (#94).
 Kindly have a look into it and merge it.
Thank you.

**Comment by SobhanBera** [comment]
You're most welcome.
