### ISSUE TITLE
Huffman Coding in C++

### ISSUE THREAD

**Issue by sobhanbera** [sobhanbera/algorithms#40]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by kranand6** [comment]
Hi @SobhanBera, I am willing to work on Huffman Coding in C++. Can this issue be assigned to me?  
Thank you!
