### ISSUE TITLE
Huffman Coding in Java

### ISSUE THREAD

**Issue by SobhanBera** [SobhanBera/algorithms#41]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by AryashDubey** [comment]
Hey Can You Assign It to Me Please!?

**Comment by AryashDubey** [comment]
Hey Can You guide me how 
![ERROR](https://user-images.githubusercontent.com/70095055/95187314-a3fce880-07e8-11eb-9875-dc32184fc15c.jpg)
to commit changes its giving me error

**Comment by Kirty-Goyal** [comment]
Can I work on this?
