### ISSUE TITLE
Quick Sort and Sieve of Eratosthenes in C++

### ISSUE THREAD

**Issue by SobhanBera** [SobhanBera/algorithms#44]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by AkankshaJolly** [comment]
Hey, I would like to work on this issue. Can you assign this to me?

**Comment by AkankshaJolly** [comment]
> #### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)
> * [x]  I searched or browsed the repo’s other issues to ensure this is not a duplicate
> * [x]  Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)
> * [x]  I will send my PR only after I'm assigned to this issue by any maintainer
> * [x]  Assign this issue to me (I want to work on this)
> * [x]  I ensure that I am not already assigned to 2 or more issues

**Comment by AkankshaJolly** [comment]
Done #44. Please review, thanks.
