### ISSUE TITLE
Quick Sort and Sieve of Eratosthenes in JS

### ISSUE THREAD

**Issue by sobhanbera** [sobhanbera/algorithms#47]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by SubhamChoudhury** [comment]
please assign it to me.
