### ISSUE TITLE
Dijkstra Algorithm in Javascript

### ISSUE THREAD

**Issue by sobhanbera** [sobhanbera/algorithms#64]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by MeetMangukiya7** [comment]
I would love to do this. and also I have very good knowledge in ds & algorithm.

**Comment by adhammo** [comment]
Please, assign me to this issue. I am experienced in JavaScript and path finding algorithms. I can give you minimal and clean code. also written in ES6 if desired.

**Comment by laurairene785** [comment]
> #### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)
+ [ ]  I searched or browsed the repo’s other issues to ensure this is not a duplicate
+ [ ]  Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)
+ [ ]  I will send my PR only after I'm assigned to this issue by any maintainer
+ [ ]  Assign this issue to me (I want to work on this)
+ [ ]  I ensure that I am not already assigned to 2 or more issues
