### ISSUE TITLE
Counting Sort in C++

### ISSUE THREAD

**Issue by sobhanbera** [sobhanbera/algorithms#70]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by kashc11** [comment]
I'd like to contribute to this.

**Comment by shivam28singh** [comment]
I would like to work on this issue. please assign it to me.

**Comment by chiillax** [comment]
Could you please assign me for this task ?
