### ISSUE TITLE
BST in Java

### ISSUE THREAD

**Issue by SobhanBera** [SobhanBera/algorithms#79]
#### This issue is about [Algo/DS Name/Question Name](link to resource for the Algo/DS/Question)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

-   [ ] Assign this issue to me (I want to work on this)

-   [ ] I ensure that I am not already assigned to 2 or more issues

**Comment by laurairene785** [comment]
> #### Este problema es sobre [Algo / DS Name / Question Name] (enlace al recurso para Algo / DS / Question)
> * 

 [ *]  Busqué o examiné los otros problemas del repositorio para asegurarme de que no sea un duplicado

> * [ *] El título del problema está en formato `[Algo/DS Name] in [Language]`(por ejemplo: - BubbleSort en Java)
> * [ *]  Enviaré mi PR solo después de que un mantenedor me asigne este problema
> * [ *]  Asignarme este problema (quiero trabajar en esto)
> * [ *]  Me aseguro de que no estoy asignado a 2 o más problemas.

**Comment by laurairene785** [comment]
> #### Este problema es sobre [Algo / DS Name / Question Name] (enlace al recurso para Algo / DS / Question)
> * [ *]  Busqué o examiné los otros problemas del repositorio para asegurarme de que no sea un duplicado
> * [ *] El título del problema está en formato `[Algo/DS Name] in [Language]`(por ejemplo: - BubbleSort en Java)
> * [* ]  Enviaré mi PR solo después de que un mantenedor me asigne este problema
> * [ *]  Asignarme este problema (quiero trabajar en esto)
> * [* ]  Me aseguro de que no estoy asignado a 2 o más problemas.

**Comment by laurairene785** [comment]
> #### Este problema es sobre [Algo / DS Name / Question Name] (enlace al recurso para Algo / DS / Question)
> * [ ]  Busqué o examiné los otros problemas del repositorio para asegurarme de que no sea un duplicado
> * [ ] El título del problema está en formato `[Algo/DS Name] in [Language]`(por ejemplo: - BubbleSort en Java)
> * [ ]  Enviaré mi PR solo después de que un mantenedor me asigne este problema
> * [ ]  Asignarme este problema (quiero trabajar en esto)
> * [ ]  Me aseguro de que no estoy asignado a 2 o más problemas.

**Comment by laurairene785** [comment]
> #### Este problema es sobre [Algo / DS Name / Question Name] (enlace al recurso para Algo / DS / Question)
 [> * ]  Busqué o examiné los otros problemas del repositorio para asegurarme de que no sea un duplicado
 [> * ] El título del problema está en formato `[Algo/DS Name] in [Language]`(por ejemplo: - BubbleSort en Java)
 [> *  ]  Enviaré mi PR solo después de que un mantenedor me asigne este problema
[> *  ]  Asignarme este problema (quiero trabajar en esto)
 [> * ]  Me aseguro de que no estoy asignado a 2 o más problemas.

**Comment by laurairene785** [comment]
> #### Este problema es sobre [Algo / DS Name / Question Name] (enlace al recurso para Algo / DS / Question)
+ [ ]  Busqué o examiné los otros problemas del repositorio para asegurarme de que no sea un duplicado
+ [ ] El título del problema está en formato `[Algo/DS Name] in [Language]`(por ejemplo: - BubbleSort en Java)
+ [ ]  Enviaré mi PR solo después de que un mantenedor me asigne este problema
+ [ ]  Asignarme este problema (quiero trabajar en esto)
+ [ ]  Me aseguro de que no estoy asignado a 2 o más problemas.
