### ISSUE TITLE
Binary Search in golang

### ISSUE THREAD

**Issue by Ayush-Mahajan** [sobhanbera/algorithms#91]
#### This issue is about golang

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [X] I will send my PR only after I'm assigned to this issue by any maintainer

-   [X] Assign this issue to me (I want to work on this)

-   [X] I ensure that I am not already assigned to 2 or more issues

**Comment by imravichhetri** [comment]
@Ayush-Mahajan Can you Assign this issue to me? and add tag hacktoberfest?
